---
- name: Restart CICS region
  hosts: zos_host
  gather_facts: no
  environment: "{{environment_vars}}"

  tasks:
     - name: Stop CICS region immediately using job ID
       ibm.ibm_zos_core.zos_operator: 
        cmd: "s {{cics_region}}"