---
- name: CSD Install

  hosts: "zos_host"
  gather_facts: "false"
  environment: "{{environment_vars}}"

  tasks:
    ############################################################################
    # Install module dependencies
    ############################################################################
    - name: Make sure CMCI module dependencies are installed
      ansible.builtin.pip:
        name:
          - requests
          - xmltodict
          - typing;python_version<"3.5"

    - name: "HTTP Create progdef"
      delegate_to: "localhost"
      ibm.ibm_zos_cics.cmci_create:
        context: "{{ context }}"
        cmci_host: "{{ cmci_host }}"
        cmci_port: "{{ cmci_port | int }}"
        cmci_user: "{{ cmci_user | default(omit) }}"
        cmci_password: "{{ cmci_password | default(omit) }}"
        type: "CICSDefinitionProgram"
        attributes:
          name: "{{ program }}"
          csdgroup: "{{ csdgroup }}"
        create_parameters:
          - name: "CSD"