---
- name: Modify line in dataset after {{expression_to_insert_after}}
  hosts: zos_host
  gather_facts: no
  environment: "{{environment_vars}}"
  tasks:
    - name: Insert a line where the expression is found
      ibm.ibm_zos_core.zos_lineinfile:
        src: '{{dataset_src}}'
        line: "{{line_replacement}}"
        insert_after: '{{expression_to_insert_after}}'
        state: present
