---
- name: Modify line in dataset after
  hosts: zos_host
  gather_facts: no
  environment: "{{environment_vars}}"
  
  tasks:
    - name: Insert a line where the expression is found
      ibm.ibm_zos_core.zos_lineinfile:
        src: '{{dataset_src}}'
        regexp: '{{expression_to_insert_after}}'
        line: "{{line_replacement}}"
        force: true
        state: present
