---
- name: Modify line in dataset after
  hosts: zos_host
  gather_facts: no
  environment: "{{environment_vars}}"
  
  tasks:
  #This task replace the last line where {{expression_to_insert_after}} is found with {{line_replacement}}
    - name: Insert a line where the expression is found
      ibm.ibm_zos_core.zos_lineinfile:
        src: '{{dataset_src}}'
        regexp: '{{expression_to_insert_after}}'
        line: "{{line_replacement}}"
        force: true
        state: present

    - name: "Stop CICS region immediately using job ID"
      ibm.ibm_zos_cics.stop_region:
       job_name: "{{cics_jobname}}"

       

