---
- name: insert block in dataset 
  hosts: zos_host
  gather_facts: no
  environment: "{{environment_vars}}"
  
  tasks:
  #This task inserts a block after an expression
    - name: Insert a block where the expression is found
      ibm.ibm_zos_core.zos_blockinfile:
        src: '{{dataset_src}}'
        insertafter: "{{expression_to_insert_after}}"
        block: "{{block_to_insert}}"
        force: true
        state: present  
      register: blockinfile_result

    - name: Debug results of blockinfile
      ansible.builtin.debug :
       var: blockinfile_result