---
- name: Modify line in dataset after
  hosts: zos_host
  gather_facts: no
  environment: "{{environment_vars}}"
  
  tasks:
    - name: Insert a line where the expression is found
      ibm.ibm_zos_core.zos_lineinfile:
        src: "IBMUSER.ANSIB.TESTLIF(TEST)"
        regexp: "(.*{{expression_to_insert_after}})(.*)"
        line: '\1Aaaaaaaa\3'
        backrefs: true
      register: lineinfile_result
      
    - name: Debug output
      debug:
        var: lineinfile_result