---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  vars:
    job_name: "{{ job_name_survey }}"
    job_contents: "{{ job_contents_survey }}"
  environment: "{{ environment_vars }}"
  tasks:

    - name: Copy JCL from template
      zos_copy: 
        content: "{{ job_contents }}"
        dest: "/tmp/{{ job_name }}.jcl"
        encoding:
          from: ISO8859-1
          to: IBM-037
        force: true
